kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
data:
  AVP_VAULT_ADDR: aHR0cDovL3ZhdWx0LmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6ODIwMA==   
  AVP_TYPE: dmF1bHQ=
  AVP_AUTH_TYPE: azhz
  AVP_K8S_ROLE: YXJnb2Nk